external_data_config:
  external_data_csv: data/external/loan.csv

raw_data_config: 
  raw_data_csv: data/raw/loan.csv
  model_var: ['Gender','Married','Dependents','Education','Self_Employed','ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term','Credit_History','Property_Area','Loan_Status']
  train_test_split_ratio: 0.2
  target: Loan_Status 
  random_state: 111
  new_train_data_csv: data/raw/loan_new.csv

processed_data_config:
  train_data_csv: data/processed/loan_train.csv
  test_data_csv:  data/processed/loan_test.csv

interim_data_config:
  train_data_csv: data/interim/loan_train.csv
  test_data_csv:  data/interim/loan_test.csv

random_forest: 
  max_depth: 10
  n_estimators: 3

model_dir: models/model.joblib

reports:
  params: reports/params.json
  scores: reports/scores.json

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: model_iteration
  run_name: Random Forest
  registered_model_name: random_forest_model
  remote_server_uri: http://localhost:5000