artifact_uri: file:///F:/amudhan/mlops/loan_prediction/mlop_lifecycle1/mlruns/1/9b801fed97014b51a9a9773fa0bf4a93/artifacts
end_time: 1647948091880
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 9b801fed97014b51a9a9773fa0bf4a93
run_uuid: 9b801fed97014b51a9a9773fa0bf4a93
source_name: ''
source_type: 4
source_version: ''
start_time: 1647948079306
status: 3
tags: []
user_id: LENOVO PC
