artifact_uri: file:///F:/amudhan/mlops/loan_prediction/mlop_lifecycle1/mlruns/1/28db568ccea74cf8ac6b69aca59fc165/artifacts
end_time: 1648889748103
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 28db568ccea74cf8ac6b69aca59fc165
run_uuid: 28db568ccea74cf8ac6b69aca59fc165
source_name: ''
source_type: 4
source_version: ''
start_time: 1648889712888
status: 3
tags: []
user_id: LENOVO PC
