artifact_uri: file:///F:/amudhan/mlops/loan_prediction/mlop_lifecycle1/mlruns/1/03267fb694cf4b9ea43807a3a6d84086/artifacts
end_time: 1647753793026
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
name: ''
run_id: 03267fb694cf4b9ea43807a3a6d84086
run_uuid: 03267fb694cf4b9ea43807a3a6d84086
source_name: ''
source_type: 4
source_version: ''
start_time: 1647753778574
status: 3
tags: []
user_id: LENOVO PC
